require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Style/Documentation:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false
